---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr
  namespace: home-system
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-iscsi-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-cache
  namespace: home-system
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-iscsi-csi
