apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: home-system
type: Opaque
stringData:
    EMQX_DASHBOARD__DEFAULT_USERNAME: ENC[AES256_GCM,data:ZJ5eMaY=,iv:DuxhXZxCFFiekdKo/1MwDaXhwJLdbvH4HOsOB3xh3w8=,tag:Gku9TThVnoSEPukjHQ5k3w==,type:str]
    EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:wGePi0I=,iv:XjIObz50jqSCgC17niK0/STop1jL8crwHSniIElwVuc=,tag:oeh+r65XXEJDkuWRYFvxJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-08T00:17:43Z"
    mac: ENC[AES256_GCM,data:0BvS2VQpZWNSoMrM5l3WX3h0r4GK9O3kIb7kAr0wM4sabP75hu8h4x1BvR9ZyE/n+7ITp4J2ggiZkGV1APwLeTvEcPnk4++HEFHHjr16yRL39opEARRbMKPQmt4gjyQ8u4Zr8FOO1jQD3bjIv7Lq7GaE6iuVTtyJW1eIC+aKQds=,iv:1dP8d3OpDANjuxnqnXbxO7MVv+EJegoGcaFPo5wnZsI=,tag:zds8o/j1jOfQFDh15HSmIg==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: emqx-init-user-secret
    namespace: home-system
type: Opaque
stringData:
    init-user.json: ENC[AES256_GCM,data:zH/4DEmDDbj5faqEHMxNF2X0XIaRAR+9MalzP/NiZI0EzRGbI3ecKjgV6GnurZOUmRj3jpicwHudabV1LjKgkzyK,iv:qgSdMFd5CTU1muqIWQPjAZbF6GCuVqwdPmg8ER1ubsE=,tag:hDq1gYAQQWDu82Otqkunyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-08T00:17:43Z"
    mac: ENC[AES256_GCM,data:0BvS2VQpZWNSoMrM5l3WX3h0r4GK9O3kIb7kAr0wM4sabP75hu8h4x1BvR9ZyE/n+7ITp4J2ggiZkGV1APwLeTvEcPnk4++HEFHHjr16yRL39opEARRbMKPQmt4gjyQ8u4Zr8FOO1jQD3bjIv7Lq7GaE6iuVTtyJW1eIC+aKQds=,iv:1dP8d3OpDANjuxnqnXbxO7MVv+EJegoGcaFPo5wnZsI=,tag:zds8o/j1jOfQFDh15HSmIg==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
