---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-system

resources:
  - helmrelease.yaml
  - pvc.yaml
  - secret.enc.yaml

configMapGenerator:
  - name: recyclarr-configmap
    files:
      - recyclarr.yml=./resources/recyclarr.yml

configurations:
  - kustomizeconfig.yaml
