---
# yaml-language-server: $schema=https://kubernetes-schemas.raspbernetes.com/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gha-runner-scale-set-charts
  namespace: flux-system
spec:
  type: oci
  interval: 2h
  url: oci://ghcr.io/actions/actions-runner-controller-charts
