---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/namespaces/base/network-system/k8s-gateway/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
