apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
    namespace: home-system
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:7GknuVW97TPQsE1wO0YRvGdy50yMYGoEKRDzlQmhiiQ=,iv:8UdW81KS8kDiDM243mCb3YZJjLCdj2Xwrz598y4Jzcc=,tag:SUQ4qlndSZ2gnLDnz8f14Q==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:ud2KDf0nVS5sulBPZNdZM4de/zFogW0b2X+kpM1V/V0=,iv:7qG28KNU8dilnO4kLMuzZMDjODJoEWtS8M26YEm4M+U=,tag:HObu4Xqh47uf3zPEYusO8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-17T10:03:17Z"
    mac: ENC[AES256_GCM,data:iWBYMNY4/TusjBHIVH5TIdMHo2kF57ZiiSwj7CvwSj4peeTBrenJxrM/picyjMHENZFGBmb/IafT5cBPNbmXoyTR91n7WJ9g0CjM+KO2A/+UZ19MNhNfGW8XUmmLm/9lkwC89tOPue5rcbLQ/UDbnfnVxtFayxNxFZbzy2dLLKE=,iv:7vBitXOLKJAATC0HIbMJw3G/HJ3r7AMhX4thlQ2JgO0=,tag:lmYihErxMsRIii4C7vMfTw==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
