---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: observability
  labels:
    substitution.flux/enabled: true
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/namespaces/base/observability/kube-prometheus-stack/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-addons
  namespace: observability
  labels:
    substitution.flux/enabled: true
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/namespaces/base/observability/kube-prometheus-stack/addons"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
