---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - helmrelease.yaml
  - virtualservice.yaml

configMapGenerator:
  - name: kromgo-config
    files:
      - config.yaml=./resources/config.yaml

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configurations:
  - kustomizeconfig.yaml
