---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx
  namespace: home-system
  labels:
    substitution.flux/enabled: true
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/namespaces/base/home-system/emqx/app"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-cluster
  namespace: home-system
  labels:
    substitution.flux/enabled: true
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/namespaces/base/home-system/emqx/cluster"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
