---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: enemy-territory
  namespace: game-servers
  annotations:
    external-dns.alpha.kubernetes.io/target: "et.${CLUSTER_DOMAIN}"
    external-dns.alpha.kubernetes.io/external: 'true'
spec:
  endpoints:
    - dnsName: "et.${CLUSTER_DOMAIN}"
      recordType: CNAME
      targets:
        - "${CLOUDFLARED_TUNNEL_ID}.cfargotunnel.com"
