---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enemy-territory
  namespace: game-servers
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-iscsi-csi
