---
# yaml-language-server: $schema=https://kubernetes-schemas.raspbernetes.com/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubefed-charts
  namespace: flux-system
spec:
  interval: 2h
  url: https://raw.githubusercontent.com/kubernetes-sigs/kubefed/master/charts
