---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - actions-runner-controller.yaml
  - backstage-charts.yaml
  - backube-charts.yaml
  - bitnami-charts.yaml
  - bjw-charts.yaml
  - cilium-chart.yaml
  - coredns-charts.yaml
  - crossplane-charts.yaml
  - crowdsec-charts.yaml
  - csi-driver-nfs-chart.yaml
  - democratic-csi-charts.yaml
  - descheduler-chart.yaml
  - dex-chart.yaml
  - emberstack-charts.yaml
  - emqx-charts.yaml
  - external-dns-chart.yaml
  - fairwinds-charts.yaml
  - falco-security-charts.yaml
  - flagger-charts.yaml
  - fluxcd-kustomize-mutating-webhook-chart.yaml
  - gatekeeper-charts.yaml
  - grafana-charts.yaml
  - ingress-nginx-chart.yaml
  - istio-charts.yaml
  - jaegertracing-charts.yaml
  - jetstack-charts.yaml
  - kiali-charts.yaml
  - kubefed-charts.yaml
  - kubereboot-charts.yaml
  - kubernetes-stable-charts.yaml
  - kyverno-charts.yaml
  - litmuschaos-charts.yaml
  - loft-charts.yaml
  - mayastor-chart.yaml
  - metallb-charts.yaml
  - metrics-server-chart.yaml
  - minecraft-server-charts.yaml
  - node-feature-discovery-chart.yaml
  - oauth2-proxy-chart.yaml
  - openebs-charts.yaml
  - openfaas-charts.yaml
  - otel-charts.yaml
  - postfinance-charts.yaml
  - rook-ceph.yaml
  - sealed-secrets-charts.yaml
  - secrets-store-csi-driver-chart.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - vernemq-charts.yaml
  - vmware-charts.yaml
  - xunholy-charts.yaml
