---
# yaml-language-server: $schema=https://kubernetes-schemas.raspbernetes.com/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy-chart
  namespace: flux-system
spec:
  interval: 2h
  url: https://oauth2-proxy.github.io/manifests
