---
# yaml-language-server: $schema=https://kubernetes-schemas.raspbernetes.com/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vernemq-charts
  namespace: flux-system
spec:
  interval: 2h
  url: https://vernemq.github.io/docker-vernemq
