---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-login
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ghcr-login
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"flux","password":"{{ .FLUX_GITHUB_TOKEN }}","auth":"{{ printf "flux:%s" .FLUX_GITHUB_TOKEN | b64enc }}"}}}
  data:
    - secretKey: FLUX_GITHUB_TOKEN
      remoteRef:
        key: flux
        property: FLUX_GITHUB_TOKEN
