---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./externalsecret-ghcr.yaml
  - ./helmrelease-postgrest.yaml
  - ./helmrelease-realtime.yaml
  - ./helmrelease-reporter.yaml
  - ./helmrelease-web.yaml
  - ./httproute.yaml
