---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft
  namespace: game-servers
  labels:
    substitution.flux/enabled: true
spec:
  interval: 5m
  path: "./kubernetes/namespaces/base/game-servers/minecraft/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
