---
connectivity:
  checker:
    target: 192.168.10.1:53
    interval: 1m
endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.pipitonelabs.com
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"

  - name: heartbeat
    group: external
    ui:
      hide-hostname: true
      hide-url: true
    url: ${STATUS_PAGE_HEARTBEAT_URL}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"

  - name: "*.pipitonelabs.com"
    group: certificates
    url: "tls://external.pipitonelabs.com:443"
    interval: 24h
    conditions:
      - "[CONNECTED] == true"
      - "[CERTIFICATE_EXPIRATION] > 336h"
    alerts:
      - type: pushover

metrics: true

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

#storage:
#  type: postgres
#  path: ${DB_URI}
#  caching: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://raw.githubusercontent.com/pipitonelabs/k8s-gitops/main/docs/assets/mars.png
  link: https://github.com/pipitonelabs
  buttons:
    - name: Github
      link: https://github.com/pipitonelabs
    - name: Homelab
      link: https://github.com/pipitonelabs/k8s-gitops

web:
  port: ${GATUS_WEB_PORT}