context: talos-default
contexts:
    talos-default:
        endpoints:
            - 127.0.0.1
        ca: ENC[AES256_GCM,data:DhO5VdKzXxHZ0oLlerIFbTJlcW6OI3UBMdEHRE1d50/AwK9EP9ArfR0ZZ6Espi9ei7iS1uuWerN661a090xBgxikRoWi4HEkIVyx8HuinVdMPFDB6AsvR95ymzzpgdN/PfB++0APXgL0adiAe3zIZFtgaWtctVNMPInqkrbzyD8ouGOT8FipqYqd8JKm+F80yxL5X3Zc1mitu4ugIJNUCs6kRFdBG35TS0MUCoSF3P80oSKtRRBKz9qgoguUQ7G9h//Pe79YBlsVxwEPl+8VTMxrS+ku/nPk1D52JquGfQH1yTMAxFtSM2mdH4kEL6RqSxaC849WGLzCzc3UG5jHZYIGbeX2RLG1/HzOo9wrVnrcQX8H0zSEGYSEQVVY0WaF440hqXuDwG4cSLL6JGvm1aL/1Xgf3A2pML1MPz4kbIUSOTGPNH6R4gh6VkbhqGKNoEjTVNOpxFJjnYK/R5kn/RQcF5xq7sKjPXSpyhNrpzzkQ2H86b+QrolOlKx5Fu/tQQr+qZPizoXEbwf31v0Cex1Akylcgy7dvl1Xfwwmr5id2rGUZRO9RmclpykccQ0S96JTTlpIJ7wpyGVUWzoK8Q+JKNn0jvRUKldGWWPJTt6XzkP1U//eEOs3e8yOfy787yE66TC4o+69v4ESCsBK2Ys1PlM/lIRMg7cmvRTB1q8bkFB1sFh2MKaAfHt2twGySoEkIl9xUh4XDgo+fRlBb4ElEGy4R1XqGPElxuc2AMXrbgJMwWjwKBQIBW63FcPO656bbgAwMNR8FPYKwMwE3N3q2B3e68Qw8iV0IBdpDz+s/c8PLdk14THzb5D5ZP1nc+XxqJrXd1Jd5uq/iq+E+lqORQtK4E+cfqltRd8TVouAByQn,iv:QAEU1Lt4SOXR1C8roW7mOGBH16poDpCubC976X2iFIU=,tag:PuPdtDMBgM0xgbmr4Fsa0g==,type:str]
        crt: ENC[AES256_GCM,data:Wwq1QjTUTRtB3BAjNIyyxMHHRQQ1CrwYeePE2Ly9agJrK0dByG5qZtLhagI1Ou5baGV2g0heUyQeI7FRwCJ67c5kwPJF6gMitAOj/AQ9m2zCvcg0cALsH3qAzGuQ52do2mIz+kn/oGGR40MlHifjdR5VMs8ETAus42MfN79WZ2kQou47TBDTf0MERT5Fj+5YzVzjS8VqF1KnquTQ0P9WgspE0RKkgrf41Wr4hEoFNFCSzkcdWbTP0cOrZic2iJTbxbB0+Tr8U+VI8uhGM9EMc3rrLYgmjOGfLRlPnBHY5oKpv+m+8DxIImb/lpmearJohXnyaiTjaMR3MkriYSkkbHTAtYHBpC91mSjN4puk2S0Xj2D+u3XRwxcv8Kwcz9uyYkWKUvbAEdaYio2rgnfTpHsjcmIn4+8NEjfwiOmXSSgof7GDqvyq0myqupplhMkmGhyUOtUU7uiHE/Nr2Ah/5C68YaCkeHnrkE5RxPml76/51poIBWevG+E3zTiVs+Jh8bpmlAJbuz3FuL6tXgdtd2/6edhbjo56CD1mIPEQWNE46urWAuH2YdEjYVCrg2sUFJfyRM3aq9Si3doeoZAsXXuuxMoBV5FGtQD7xrrw6tC5GZSp3Jybjz+VkA4rPNE87o8mmAhPpbsp8Fle3J2VgkTDl3AviiAQOE4CKMZHGH+MooOmkvtEc8zw7CLScguLYxNqHCKHdlwWh1ZmXEBypvWLtoOeoBrwNLoza0pBT7T/zGaYihnCrOooRvtlV5WA5Xcyc0CZtSn8/egPqj6/sBrV6x1HWPMjF+Fic1ahMpPAvVolLWeurQ==,iv:xuUp2c9X70ZPKIOu2LNhu0sG2ZaMJ+FjHTwhhIb6ecQ=,tag:bO/1spiIxNuetN5On8CwQw==,type:str]
        key: ENC[AES256_GCM,data:EtOYqikMIcpjrN4nN6c9nHdAx2tVpfgUiGjb3sLu9HgUdq24GzFxW7RoZGFsatIq5p72x+axKUUNXYMgWE4p6CtfZG4f6mzFhpS3MWbFrGoND1QJdghF86+7IYwptN3alZ73N43powd1okd8/hnkFmVLJVvVPaztjpySTynbkGUypqvESu7mk0oFqWNj9GmYWOIA8shICOcrluV57HAdU3CTIfhPen90pdcqb5M2ahQj4pLa,iv:5VXvmN6ZxhEsQ39reJE+LaAYNXtZFT7syxxOCqQm+7Q=,tag:Q71BJfpw1ift5o6h3wJt3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-04T23:34:43Z"
    mac: ENC[AES256_GCM,data:cy3km17xKtsEv9/8b/DhtXmB+yueEaUr95MnYaDDgx750rg/l3P+abX2zzG1AXPdWh9NrjsSID6g9BK1g4pbrvUaV9r1g/Gr/qVFfdZV6D6K/z+tqhNF+jy4PC90bk5Pbm6VEhapRn2RzK3eEOJf3iDZLQyplJNTJL1nr3hMJNI=,iv:50xOxcGA7t2vssvHJ/hPMeUQYt9zcHT5Slu6Se1ShVc=,tag:7l9BbC3HK+5gR83irBKXxw==,type:str]
    pgp:
        - created_at: "2023-03-02T05:49:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwARAA2ozZJ62IZZ/ctHFq+kC3c4KsAMf8WS1z9UacqaDbmMio
            nVD6+N24lxwAUaSqm85gDJJDw6qk9T8W+crlf0VzcHFZZaLBnVw34nTnQM+Z+PgD
            lXNvGiF77lBU453DKJkReRKSKwOzOKBvPPLo9qy2GVuqxrvWvVQgu5P2ZPwTCnbP
            FTvRrrCb/5mNN4P1twZPYp0oy8lV176ewIlZoW44U4o7bZ0dvAC/zKn0AfUr/Ym6
            z68QVIZMGq4SHc38S9Df5VStcEl36WXhG/NN9QR7By/mHlZho0gUEKGKcVrNvvNB
            5gNST3/S5R8KivqblOKAjHNgfGNko/Zse6livFj0yfx/R+ebFMtkc1XkypuGw1z7
            8EE3yIDp7G15pIENPp6ysDG8WGiuZVWTWRMSCT3AeA77JuuTLsyBd4XjacmWnFjK
            R6uh+j8TkOH53Tw4vg4VpqfF4d6WA3OkX7RLOh9mKzfXUernCSR76N95j5uTt6lu
            zUDOGdZG877XIHUMeQEnW+aVkKDJojFrt1VnbFMd62Esm3+nXmd6mQGBp93R9BN6
            na+swaivekXRGzOEXz4kjpS3tBunG+FGLx4r0mcY6EUouK2+os0fBz5zoXC0/cZF
            LdjWwEeAS7vSFRN8KMuXZ394DRbKQKe9ZnAqNbFc9saiVpsfwKNdh/y3zLXej57S
            XgHwQG/8bsgJ91eoOLPSD6AnprL+Odjt00wyCC8ZRfQRR5uDUuL3SYOhByHMprXv
            NzNDTRNljLAd5i1fIZe6U6It68gM3UPNaKqx9kj3+Zd8p/WnRbm9YZtIMnLv5qw=
            =M0cI
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$))
    version: 3.7.1
