# TODO: Investigate the best way to enable this through using the helm charts.
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-csr
  namespace: network-system
spec:
  interval: 5m
  path: "./kubernetes/namespaces/base/network-system/istio-csr/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: network-system
