apiVersion: v1
kind: Secret
metadata:
    name: driver-config
    namespace: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:59Ska9PUdaD+4pHojl/GHEYowoIvIM/0tJ97GVseFfpWx92Hzm0X4r8qZ2oAEOt0ULB77xO3hu1FyIcvH6BU7hHeCwzB3He4/e8I881V2YU5nuyi5rGi+DCJLX9u78BCd7DkV7CFpQ1dHv1NgBRm+MMzvQg93MiZuErHEFHlvuJrH4uTgJ6CTBthvr4gqBuxLNpB0V7KtfUDsCIg7lbg39+essIbDvTT1B7loUg3mE3hLFj2AOdodNvdD5aLUKrV9GDR50xvmQ6c7r3Ru6pHPIVRff8+wkS8eectc+0WlWK1+QsTCV2bhT4pH3/7KPhGKVrcbuGKuxf/XD5h9DPaIqASJ1f/kYLorUtoZ6ED1jXFE3xNc7mkLRseAQNGwKnS9nxRPPlqUx4FAdhdjx3r4koY2EzV8WftGHQ95X+89K9g2WbidM7U+DsSBAQkg8HozeLA/d1JzrcEUey0rWgM9NitD7llc0TnqYjvXEcDzTdgSkhNsvOjca9ziDjOQgv8p6GmFhq5SuI6zwC0G9R/Eak+yyhoJ9ktSinmgIYwiMTa8hJmsm588F1tHvrzYZdpoC305S4y8A1JBMwbDnJ0uY47M/i4z5oCSQskvqs6maZGyug7GGmEwL8b22tF9MQxCoD6WJ2+wEe7ecbkis8wC8KtTB2aAuR3dfbXrl3DUF0+BKdWD5Axw22d2y+PMU2j43eEPLxOvAUWAyAEnwSuepx3w87gTAg+nvbiC7AZOv7UsNA4JStUT8yFfMV+f88mrrH3UgtCPzmrq2/pJquyZnOCGXvHpyiulLvc3eB8BBrgFIFkxuA62KieZnjqhD0PTboN9iURG6F1Df85/HUQ/NljR9s5Uz077bUBXU2L1+f6PrJMlJHBZHXVSL5d8lih3ceLCgjpjV9bBPgHKHcHx7tJUVh48rj/8DeUF1WMI0QCqsgP1n0ppx33xP3B+5Ppl9sQLQ==,iv:v5lGOpZBLMODzR7hA9w1iugQ45qr5OJpfLN/8vOscQ0=,tag:kVqTQJbzi/ROxx9r00a6hA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-16T22:29:13Z"
    mac: ENC[AES256_GCM,data:Q32/vUS9uOJU+wH8xCdn6EIxywYq5jMms5EpFu2JzgeIduzqZcFuJfl44d8neBTDJKpvfh2K8oG6LtG7IOXSZmWdWaWWotiBxLLhgLAOh/deIY8XMIdKGmPsITX7kNFFeI4R8QI3IennCNxJP7LLFOp9hG8JZK0stByO1V+kGWQ=,iv:9lKeNszMyF6OXNgL1gvdOHlVJUshrbVMoonYswN1dFY=,tag:E2CIShrEovHN7sQ/wRhHUw==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
